version: '3'
services:
  mysql:
    image: "mysql:5.7.10"
    container_name: "typeorm-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    volumes:
      - ./data/mysql/:/var/lib/mysql
    expose:
      - "3306"
  app:
    image: "dhayaec/book-api"
    container_name: "book-api"
    ports:
      - "4001:4000"